# Site settings
title: Blank's Blog
SEOTitle: Blank的博客 | Blank's Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "Android开发工程师 | Android & Web Lover，Software Engineer | 这里是 @Blank 的个人博客，Find more，get more。"
keyword: "Blank, @blank, Blank的博客, Blank Blog, 博客, 个人网站, 互联网, Android"
url: "https://blankting.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
zhihu_username:     blankting
github_username:    blankting
facebook_username:  tingblank
csdn_username:      Blank557
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: blankting
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 155e406932b585f1822e                            #生成的clientID
  clientSecret: 928fac110bb00689d82ae6b36490ebac3c4c0ec4    #生成的clientSecret
  repo: blankting.github.io    #仓库名称
  owner: blankting    #github用户名
  admin: blankting
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: a60a085775c768e7be4d14857f406e8fd6b73466

# Google Analytics
ga_track_id: 'UA-136297606-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "No cross, no crown<br>生活有度"
sidebar-avatar: /img/about-blank-ny.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Android Developer",
        href: "https://developer.android.google.cn"
    },{
        title: "Android Docs",
        href: "http://www.android-doc.com/reference/packages.html"
    }
]
